name: rates

volumes:
  db:
  pgadmin:

networks:
  proxy:

services:
  db:
    image: postgres:16.4-alpine
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - proxy

  pgadmin:
    image: dpage/pgadmin4:8.11
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
    volumes:
      - pgadmin:/var/lib/pgadmin
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.rule=Host(`pgadmin.$CNAME`)
      - traefik.http.routers.pgadmin.entrypoints=web
      - traefik.http.routers.pgadmin.service=pgadmin
      - traefik.http.services.pgadmin.loadbalancer.server.port=80
    networks:
      - proxy
    depends_on:
      - db

  turbo:
    image: rates:turbo
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/app
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=Host(`$CNAME`)
      - traefik.http.routers.web.entrypoints=web
      - traefik.http.routers.web.service=web
      - traefik.http.services.web.loadbalancer.server.port=3000
      - traefik.http.routers.api.rule=Host(`api.$CNAME`)
      - traefik.http.routers.api.entrypoints=web
      - traefik.http.routers.api.service=api
      - traefik.http.services.api.loadbalancer.server.port=4000
    networks:
      - proxy
    depends_on:
      - db

  traefik:
    image: traefik:v3.1.2
    command:
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --providers.docker.network=proxy
      - --providers.docker.exposedbydefault=false
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.$CNAME`)
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.service=api@internal
    networks:
      proxy:
        aliases:
          - $CNAME
          - api.$CNAME
          - pgadmin.$CNAME
    depends_on:
      - turbo
