global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    static_configs:
      - targets: [localhost:9090]

  - job_name: node
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    static_configs:
      - targets: [nodeexporter:9100]
