name: api

on:
  push:
    branches:
      - main
    paths:
      - apps/api/**
      - packages/api/**
      - packages/database/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push:
    name: Prepare Docker image
    uses: ./.github/workflows/ci.yaml
    with:
      app: api
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy:
    name: Deploy
    uses: ./.github/workflows/cd.yaml
    needs: build-push
    with:
      app: api
      port: 4000
    secrets: inherit
