name: migrate

on:
  workflow_call:
  workflow_dispatch:

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  migrate:
    name: Migrate database
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            packages/database
            packages/eslint-config
            packages/typescript-config

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm
        run: |
          echo "store=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm.outputs.store }}
          key: ${{ runner.os }}-migrate-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-migrate-

      - name: Install dependencies
        run: |
          pnpm install --filter=@repo/database

      - name: Check database connection
        run: |
          pnpm db:check

      - name: Run database migration
        run: |
          pnpm db:migrate
