name: migrate

on:
  workflow_call:
  workflow_dispatch:

env:
  DATABASE_URL: postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@${{ secrets.POSTGRES_HOST }}:5432/${{ vars.PROJECT }}

jobs:
  migrate:
    name: Migrate database
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            packages/database
            packages/eslint-config
            packages/typescript-config

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm
        run: |
          echo "store=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm.outputs.store }}
          key: ${{ runner.os }}-migrate-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-migrate-

      - name: Install dependencies
        run: |
          pnpm install --filter=@repo/database

      - name: Allow database access
        run: |
          curl \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.HETZNER_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"apply_to":[{"server":{"id":${{ secrets.HETZNER_HOST_ID }}},"type":"server"}]}' \
            "https://api.hetzner.cloud/v1/firewalls/${{ secrets.HETZNER_FW_ID }}/actions/apply_to_resources"

      - name: Check database connection
        run: |
          pnpm db:check

      - name: Run database migration
        run: |
          pnpm db:migrate

      - name: Disallow database access
        run: |
          curl \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.HETZNER_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"remove_from":[{"server":{"id":${{ secrets.HETZNER_HOST_ID }}},"type":"server"}]}' \
            "https://api.hetzner.cloud/v1/firewalls/${{ secrets.HETZNER_FW_ID }}/actions/remove_from_resources"
