name: web

on:
  push:
    branches:
      - main
    paths:
      - apps/web/**
      - packages/api/**
      - packages/ui/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push:
    name: Prepare Docker image
    uses: ./.github/workflows/ci.yaml
    with:
      app: web
      build-args: |
        NEXT_PUBLIC_BASE_URL=${{ vars.NEXT_PUBLIC_BASE_URL }}
        NEXT_PUBLIC_API_HOST=${{ vars.NEXT_PUBLIC_API_HOST }}
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy:
    name: Deploy
    uses: ./.github/workflows/cd.yaml
    needs: build-push
    with:
      app: web
      port: 3000
    secrets: inherit
